export default {
  content: "",
  options: [],
  user_id: "123",
  bot_id: "",
  headers: {
    authorization: "", // "Bearer " + token,
    "Content-Type": "application/json",
  },
  content_param: [] as object[],
  history: [] as object[],
  avatar: {
    ai: "ai",
    user: "",
  },
  icon: {
    upload: "jia",
    clear: "clear",
    send: "icon_sent",
  },
  icon_file: {
    xls: "icon-xls",
    csv: "icon-csv",
    doc: "icon-word",
    docx: "icon-word",
    pdf: "ion-pdf",
    ppt: "icon-ppt",
    pptx: "icon-ppt",
    txt: "icon-txt",
  },
  conversation_id: 0,
  user_avatar_url: "",
  user_nickname: "",
  bot_avatar_url: "",
  bot_nickname: "",
  conversation_content: "",
  limit: 50,
  after_id: null,
  has_more: false,
  is_done: false,
  chat_id: 0,
  stop: false,
  upload_hover_title:
    "支持上传的文件格式：文档：DOC、DOCX、XLS、XLSX、PPT、PPTX、PDF、CSV 图片：JPG、JPG2、PNG、GIF、WEBP、HEIC、HEIF、BMP、PCD、TIFF",
};
